### ISSUE TITLE
ipinfo returns no results in certain circumstances

### ISSUE THREAD

**Issue by ghost** [LVPlayground/bot-saber#4]
It seems that in some instances, ipinfo will not return results when I think it should.

[16:00] @Deer_Hunter !ipinfo playername
[16:00] <+Saber> \* IPs with name "playername": 192.168.1.1 (x4) (US)
[16:00] @Deer_Hunter !ipinfo 192.168.1.1
[16:00] <+Saber> \* No results found.

An IP address for "playername" was found, but when the IP found was looked up, there were no matches. 

(I can provide the actual IP address / player nick used in this example over IRC, not posting here for privacy reasons)

**Comment by debuggest3** [comment]
I'd love to have the actual data for this issue so I can take a better look at what is going on.

**Comment by debuggest3** [comment]
Likely caused by mIRC colour codes. Will add a filter for these.
